examples/Models/ComplexObject.cs
public class ComplexObject
{
    public string Name {get;set;}

    public string Description {get;set;}

    public List<ComplexSubObject> SubObjects{get;set;}
}

examples/Models/ComplexSubObject.cs
public class ComplexSubObject
{
    public string SubName{get;set;}
    public string SubDescription{get;set;}

    public List<StatesObject> States{get;set;}
}

examples/Models/ErrorViewModel.cs
namespace examples.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

examples/Models/StatesObject.cs
public class StatesObject{
    public string Abbr{get;set;}
    public string Name{get;set;}
}

examples/Controllers/ExamplesController.cs
using Microsoft.AspNetCore.Mvc;

namespace examples.Controllers;

public class ExamplesController : Controller
{

    [HttpPost]
    [IgnoreAntiforgeryToken]
    public IActionResult ChangeEmail(string newEmail)
    {
        // Example of a vulnerable method

        // pretend email change code here
        return Json(true);
    }

    #region "Basic Page Action Results"
    public IActionResult NoToken()
    {
        return View();
    }
    public IActionResult InjectToken()
    {
        return View();
    }
    public IActionResult FormToken()
    {
        return View();
    }
    public IActionResult TokenHelper()
    {
        return View();
    }
    public IActionResult FormSerialize()
    {
        return View();
    }
    public IActionResult ComplexData()
    {
        return View();
    }
    #endregion


    // No Token Methods
    public JsonResult NoTokenGet()
    {
        return Json("No Token GET Request Works");
    }

    [HttpPost]
    public JsonResult NoTokenPost(string name)
    {
        return Json("No Token POST Request doesn't work");
    }


    // Inject Token Methods
    [HttpPost]
    public JsonResult InjectTokenPostHeader(string name)
    {
        return Json("Injected Token Via Header Works");
    }

    [HttpPost]
    public JsonResult InjectTokenPostData(string name)
    {
        return Json("Injected Token Via Data Works");
    }


    // Helper Token Methods
    [HttpPost]
    public JsonResult HelperTokenPostHeader(string name)
    {
        return Json("Helper Token Via Header Works");
    }

    [HttpPost]
    public JsonResult HelperTokenPostData(string name)
    {
        return Json("Helper Token Via Data Works");
    }

    // Form Token Methods
    [HttpPost]
    public JsonResult FormTokenPostHeader(string name)
    {
        return Json("Form Token Via Header Works");
    }

    [HttpPost]
    public JsonResult FormTokenPostData(string name)
    {
        return Json("Form Token Via Data Works");
    }

    // Form Serialize Methods
    [HttpPost]
    public JsonResult FormSerializePost(string field1, string field2, string field3)
    {
        return Json($"Form Serialize POST Works with values {field1}, {field2}, and {field3}");
    }

    // Form Complex Data Methods
    [HttpPost]
    public JsonResult ComplexDataPost(ComplexObject complexdata)
    {
        return Json(complexdata);
    }
}

examples/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using examples.Models;

namespace examples.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

examples/Views/Examples/ComplexData.cshtml
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Antiforgery
@{
    ViewData["Title"] = "Complex Data Example";
    var token = Antiforgery.GetAndStoreTokens(Context).RequestToken;
}

<h1>@ViewData["Title"]</h1>

<p>Example of ajax post using complex data models and no form.</p>

<div>
    <div class="btn btn-primary" id="btnPost">POST</div>
    <div><small class="form-text text-muted">Data is generated in JS.</small></div>
</div>

<hr />

<select id="states">
	<option value="AL">Alabama</option>
	<option value="AK">Alaska</option>
	<option value="AZ">Arizona</option>
	<option value="AR">Arkansas</option>
	<option value="CA">California</option>
	<option value="CO">Colorado</option>
	<option value="CT">Connecticut</option>
	<option value="DE">Delaware</option>
	<option value="DC">District Of Columbia</option>
	<option value="FL">Florida</option>
	<option value="GA">Georgia</option>
	<option value="HI">Hawaii</option>
	<option value="ID">Idaho</option>
	<option value="IL">Illinois</option>
	<option value="IN">Indiana</option>
	<option value="IA">Iowa</option>
	<option value="KS">Kansas</option>
	<option value="KY">Kentucky</option>
	<option value="LA">Louisiana</option>
	<option value="ME">Maine</option>
	<option value="MD">Maryland</option>
	<option value="MA">Massachusetts</option>
	<option value="MI">Michigan</option>
	<option value="MN">Minnesota</option>
	<option value="MS">Mississippi</option>
	<option value="MO">Missouri</option>
	<option value="MT">Montana</option>
	<option value="NE">Nebraska</option>
	<option value="NV">Nevada</option>
	<option value="NH">New Hampshire</option>
	<option value="NJ">New Jersey</option>
	<option value="NM">New Mexico</option>
	<option value="NY">New York</option>
	<option value="NC">North Carolina</option>
	<option value="ND">North Dakota</option>
	<option value="OH">Ohio</option>
	<option value="OK">Oklahoma</option>
	<option value="OR">Oregon</option>
	<option value="PA">Pennsylvania</option>
	<option value="RI">Rhode Island</option>
	<option value="SC">South Carolina</option>
	<option value="SD">South Dakota</option>
	<option value="TN">Tennessee</option>
	<option value="TX">Texas</option>
	<option value="UT">Utah</option>
	<option value="VT">Vermont</option>
	<option value="VA">Virginia</option>
	<option value="WA">Washington</option>
	<option value="WV">West Virginia</option>
	<option value="WI">Wisconsin</option>
	<option value="WY">Wyoming</option>
</select>				

@section Scripts
{
    <script type="text/javascript">
        $(function(){
            $('#btnPost').on('click', function(){

                var complexData = {Name: "My Object Name", Description: "My Object Description"};
                complexData.SubObjects = [];
                
                for(var i = 0; i < 5; i++){
                    var subObject = {};
                    subObject.SubName = "Sub Object " + i;
                    subObject.SubDescription = "Sub Description " + i;
                    subObject.States = [];

                    if(i == 3){
                        $("#states option").each(function(){
                            subObject.States.push({Name: $(this).text(), Abbr: $(this).val()});
                        });
                    }

                    complexData.SubObjects.push(subObject);
                }

                $.post('@Url.Action("ComplexDataPost")', {complexdata: complexData, __RequestVerificationToken: '@token'}, function(data){
                    alert("Complex Data Posted, check console");
                    console.log(data);
                });
            
            });
        });
    </script>
}

examples/Views/Examples/FormSerialize.cshtml
@{
    ViewData["Title"] = "Form Example";
}

@using(Html.BeginForm("FormSerializePost", "Examples", FormMethod.Post, new{ @id="frmSerialize"})){
    @Html.Hidden("field1", "Value1")
    @Html.Hidden("field2", "Value2")
    @Html.Hidden("field3", "Value3")
}

<h1>@ViewData["Title"]</h1>

<p>Example of ajax post grabbing the entire form and using serialize.</p>

<div>
    <div class="btn btn-primary" id="btnPost">POST - Serialize</div>
    <div><small class="form-text text-muted">Serialize the entire form (token included) and POST it.</small></div>
</div>

<hr />

@section Scripts
{
    <script type="text/javascript">
        $(function(){
            $('#btnPost').on('click', function(){

                var form = $('#frmSerialize'),
                    actionUrl = form.attr('action'),
                    dataToSend = form.serialize();

                console.log(dataToSend);
                
                $.ajax({
                    url: actionUrl,
                    method: "post",
                    data: dataToSend
                }).done(function(data) {
                    alert(data);
                });
            });
        });
    </script>
}

examples/Views/Examples/FormToken.cshtml
@{
    ViewData["Title"] = "Form Example";
}

<form method="post"></form>

<h1>@ViewData["Title"]</h1>

<p>Example of ajax post using a form. Some variations of form and beginform automatically generate tokens.</p>

<div>
    <div class="btn btn-primary" id="btnPostHeader">POST - Header</div>
    <div><small class="form-text text-muted">Use the form token in the ajax header.</small></div>
</div>

<hr />

<div>
    <div class="btn btn-primary" id="btnPostData">POST - Data</div>
    <div><small class="form-text text-muted">Use the form token in the ajax data.</small></div>
</div>

<hr />

<div>
    <div class="btn btn-primary" id="btnPostNoToken">POST - No Token</div>
    <div><small class="form-text text-muted">Won't work, check console.</small></div>
</div>


@section Scripts
{
    <script type="text/javascript">
        $(function(){
            $('#btnPostHeader').on('click', function(){
                $.ajax({
                    url: '@Url.Action("FormTokenPostHeader")',
                    method: "post",
                    headers: {"RequestVerificationToken": $('input:hidden[name="__RequestVerificationToken"]').val()},
                    data: {name: "test"}
                }).done(function(data) {
                    alert(data);
                });
            });

            $('#btnPostData').on('click', function(){
                $.post('@Url.Action("FormTokenPostData")', {name: "test", __RequestVerificationToken: $('input:hidden[name="__RequestVerificationToken"]').val()}, function(data){
                    alert(data);
                });
            });

            $('#btnPostNoToken').on('click', function(){
                $.post('@Url.Action("HelperTokenPostData")', {name: "test"}, function(data){
                    alert(data);
                });
            });
        });
    </script>
}

examples/Views/Examples/InjectToken.cshtml
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Antiforgery
@{
    ViewData["Title"] = "Inject Token Example";
    var token = Antiforgery.GetAndStoreTokens(Context).RequestToken;
}

<h1>@ViewData["Title"]</h1>

<p>Example of ajax post using AspNetCore IAntiforgery because the page doesn't have a form.</p>

<div>
    <div class="btn btn-primary" id="btnPostHeader">POST - Header</div>
    <div><small class="form-text text-muted">Use the injected token in the ajax header.</small></div>
</div>

<hr />

<div>
    <div class="btn btn-primary" id="btnPostData">POST - Data</div>
    <div><small class="form-text text-muted">Use the injected token in the ajax data.</small></div>
</div>

<hr />

<div>
    <div class="btn btn-primary" id="btnPostNoToken">POST - No Token</div>
    <div><small class="form-text text-muted">Won't work, check console.</small></div>
</div>


@section Scripts
{
    <script type="text/javascript">
        $(function(){
            $('#btnPostHeader').on('click', function(){
                $.ajax({
                    url: '@Url.Action("InjectTokenPostHeader")',
                    method: "post",
                    headers: {"RequestVerificationToken": '@token'},
                    data: {name: "test"}
                }).done(function(data) {
                    alert(data);
                });
            });

            $('#btnPostData').on('click', function(){
                $.post('@Url.Action("InjectTokenPostData")', {name: "test", __RequestVerificationToken: '@token'}, function(data){
                    alert(data);
                });
            });

            $('#btnPostNoToken').on('click', function(){
                $.post('@Url.Action("InjectTokenPostData")', {name: "test"}, function(data){
                    alert(data);
                });
            });
        });
    </script>
}

examples/Views/Examples/NoToken.cshtml
@{
    ViewData["Title"] = "No Token Example";
}

<h1>@ViewData["Title"]</h1>

<p>Example of ajax post with no token provided.</p>

<div>
    <div class="btn btn-primary" id="btnGet">GET</div>
    <div><small class="form-text text-muted">AutoValidateAntiforgeryTokenAttribute will allow GET requests without tokens.  Use ValidateAntiForgeryToken for stricter rules.</small></div>
</div>

<hr />

<div>
    <div class="btn btn-primary" id="btnPost">POST</div>
    <div><small class="form-text text-muted">Won't work, check console.</small></div>
</div>

@section Scripts
{
    <script type="text/javascript">
        $(function(){
            $('#btnGet').on('click', function(){
                $.get('@Url.Action("NoTokenGet")', function(data){
                    alert(data);
                });
            });

            $('#btnPost').on('click', function(){
                $.post('@Url.Action("NoTokenPost")', {name: "test"}, function(data){
                    alert(data);
                });
            });
        });
    </script>
}

examples/Views/Examples/TokenHelper.cshtml
@{
    ViewData["Title"] = "Token Helper Example";
}

@Html.AntiForgeryToken()

<h1>@ViewData["Title"]</h1>

<p>Example of ajax post using AntiForgeryToken helper because the page doesn't have a form.</p>

<div>
    <div class="btn btn-primary" id="btnPostHeader">POST - Header</div>
    <div><small class="form-text text-muted">Use the helper token in the ajax header.</small></div>
</div>

<hr />

<div>
    <div class="btn btn-primary" id="btnPostData">POST - Data</div>
    <div><small class="form-text text-muted">Use the helper token in the ajax data.</small></div>
</div>

<hr />

<div>
    <div class="btn btn-primary" id="btnPostNoToken">POST - No Token</div>
    <div><small class="form-text text-muted">Won't work, check console.</small></div>
</div>


@section Scripts
{
    <script type="text/javascript">
        $(function(){
            $('#btnPostHeader').on('click', function(){
                $.ajax({
                    url: '@Url.Action("HelperTokenPostHeader")',
                    method: "post",
                    headers: {"RequestVerificationToken": $('input:hidden[name="__RequestVerificationToken"]').val()},
                    data: {name: "test"}
                }).done(function(data) {
                    alert(data);
                });
            });

            $('#btnPostData').on('click', function(){
                $.post('@Url.Action("HelperTokenPostData")', {name: "test", __RequestVerificationToken: $('input:hidden[name="__RequestVerificationToken"]').val()}, function(data){
                    alert(data);
                });
            });

            $('#btnPostNoToken').on('click', function(){
                $.post('@Url.Action("HelperTokenPostData")', {name: "test"}, function(data){
                    alert(data);
                });
            });
        });
    </script>
}

examples/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h1 class="display-4">XSRF/CSRF</h1>
    <p><a href="https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-6.0">Detailed info from Microsoft docs.</a></p>
    <hr />
    <p>What is a Cross-site request forgery?</p>
    <p>Example from the link above.</p>
    <ol>
<li><p>A user signs into <code>www.good-banking-site.com</code> using forms authentication. The server authenticates the user and issues a response that includes an authentication cookie. The site is vulnerable to attack because it trusts any request that it receives with a valid authentication cookie.</p>
</li>
<li><p>The user visits a malicious site, <code>www.bad-crook-site.com</code>.</p>
<p>The malicious site, <code>www.bad-crook-site.com</code>, contains an HTML form similar to the following example:</p>
<pre tabindex="0" class="has-inner-focus"><code class="lang-html" data-author-content="<h1>Congratulations! You're a Winner!</h1>
<form action=&quot;https://good-banking-site.com/api/account&quot; method=&quot;post&quot;>
    <input type=&quot;hidden&quot; name=&quot;Transaction&quot; value=&quot;withdraw&quot; />
    <input type=&quot;hidden&quot; name=&quot;Amount&quot; value=&quot;1000000&quot; />
    <input type=&quot;submit&quot; value=&quot;Click to collect your prize!&quot; />
</form>
"><span><span class="hljs-tag">&lt;<span class="hljs-name">h1</span>&gt;</span>Congratulations! You're a Winner!<span class="hljs-tag">&lt;/<span class="hljs-name">h1</span>&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name">form</span> <span class="hljs-attr">action</span>=<span class="hljs-string">"https://good-banking-site.com/api/account"</span> <span class="hljs-attr">method</span>=<span class="hljs-string">"post"</span>&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">input</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"hidden"</span> <span class="hljs-attr">name</span>=<span class="hljs-string">"Transaction"</span> <span class="hljs-attr">value</span>=<span class="hljs-string">"withdraw"</span> /&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">input</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"hidden"</span> <span class="hljs-attr">name</span>=<span class="hljs-string">"Amount"</span> <span class="hljs-attr">value</span>=<span class="hljs-string">"1000000"</span> /&gt;</span>
    <span class="hljs-tag">&lt;<span class="hljs-name">input</span> <span class="hljs-attr">type</span>=<span class="hljs-string">"submit"</span> <span class="hljs-attr">value</span>=<span class="hljs-string">"Click to collect your prize!"</span> /&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name">form</span>&gt;</span>
</span></code></pre>
<p>Notice that the form's <code>action</code> posts to the vulnerable site, not to the malicious site. This is the "cross-site" part of CSRF.</p>
</li>
<li><p>The user selects the submit button. The browser makes the request and automatically includes the authentication cookie for the requested domain, <code>www.good-banking-site.com</code>.</p>
</li>
<li><p>The request runs on the <code>www.good-banking-site.com</code> server with the user's authentication context and can perform any action that an authenticated user is allowed to perform.</p>
</li>
</ol>

<img src='@Url.Content("~/csrf-token-1-1024x536.png")' />
<div><small>https://secumantra.com/csrf-attack-and-csrf-token/</small></div>
</div>

examples/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - examples</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/examples.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">examples</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Examples" asp-action="NoToken">No Token</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Examples" asp-action="InjectToken">Inject Token</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Examples" asp-action="TokenHelper">Token Helper</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Examples" asp-action="FormToken">Form Token</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Examples" asp-action="FormSerialize">Form Serialize</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Examples" asp-action="ComplexData">Complex Data</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - examples - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>